### ISSUE TITLE
I can't pull request in gh!

### ISSUE THREAD

**Issue by arley-dev** [Jrorp/cc-website#4]
Hindi ko alam kung bakit nagkaganito ito, pero ito yung mga alam ko na hinahanp ng git kung mag-pupull request ka at ito yung mga sumusunod na meron naman ako sa "gh" ko:

_Nasa current directory ako ng fork ko_

```
$ git branch
* main

$ git remote
origin
upstream

$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

$ git show
commit 342c5fac88092198f871f6ab3370cd72609d335f (HEAD -> main, origin/main, origin/HEAD)
Author: arley-dev <22as1597_ms@psu.edu.ph>
Date:   Tue Mar 19 19:47:33 2024 +0800

    SMTP.js is added for the form (need fix first)

diff --git a/query.js b/query.js
index a789581..86c78f0 100644
--- a/query.js
+++ b/query.js

```

Tapos ito na pagkatapos:
```
$ gh pr create
must be on a branch named differently than "main"
```

Oo, kahit sabihin mo na gamitin yung `-b main`  kung obvious naman na main ang naka-select sa command na `git branch`, same parin sya.

**Comment by Jrorp** [comment]
ok na?

**Comment by arley-dev** [comment]
Hindi parin pwede eh, same at same parin.

Tinignan ko yung [#8619](https://github.com/cli/cli/issues/8619), same issue pero sinasabi parin nila na branch name ang problema kahit hindi naman - bug yung iba, ang problema.

**Comment by Jrorp** [comment]
ulitin mo na lng ma stock ka lng dyan

**Comment by arley-dev** [comment]
Cge, cge. *  **Issue closed** *
